---

- name: Update the software package repository
  apt:
    update_cache: yes


- name: Install php & apache
  apt:  pkg={{ item }} state=installed
  with_items:
     - php5
     - php5-mysql
     - apache2
     - unzip
     - python-mysqldb
     - python-pip


- name: Start Apache
  service: name=apache2 state=started




- name: Create target directory
  file:
   path: "{{ wordpress_dest }}/wordpress"
   state: directory


- name: Extract to /var/www/html
  unarchive:
   src: "{{ wordpress_file }}/latest.zip"
   dest: "{{ wordpress_dest}}"
   remote_src: True

- name: Copy wp-config.php file
  template: src=wp-config.php.j2 dest="{{ wordpress_dest }}/wordpress/wp-config.php"
  notify:
  - restart apache2


- name: Update database credentials in the file
  replace:
   dest: "{{ wordpress_dest }}/wordpress/wp-config.php"
   regexp: "{{ item.regexp }}"
   replace: "{{ item.replace }}"
  with_items:
    - { regexp: 'database_name_here', replace: '{{ dbname }}' }
    - { regexp: 'username_here', replace: '{{ dbuser }}' }
    - { regexp: 'password_here', replace: '{{ upassword }}'}
    - { regexp: 'localhost', replace: '{{ dbhost }}'}

- name: Restart apache2 server
  service:
   name: apache2
   state: restarted
