kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: user-data-pvc
  namespace: xilium  
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: conf-data-pvc
  namespace: xilium  
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
