apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - name: logstash
        image: rsthakur83/logstash
        ports:
        - containerPort: 5000
        volumeMounts:
            - mountPath: /etc/logstash/conf.d
              name: logstash-staging-sidekiq
      volumes:
       - name: logstash-staging-sidekiq
         configMap:
            name: logstash-staging-sidekiq
            items:
             - key: config
               path: logstash.conf
