apiVersion: v1
kind: DeploymentConfig
metadata:
  name: reader
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: reader
    spec:
      containers:
      - name: reader
        image: rsthakur83/reader
