---

- name: Update the software package repository
  apt:
    update_cache: yes

- name: Install MySQL
  apt:  pkg={{ item }} state=installed
  with_items:
     - mysql-server
     - mysql-client
     - python-mysqldb

- name: Start the Mysql service
  service:
    name: mysql
    state: started
    enabled:  true

- name: Create Mysql configuration file
  template: src=my.cnf.j2 dest=/etc/mysql/my.cnf
  notify:
  - restart mysql

- name: Create Application Database
  mysql_db: name={{ dbname }} state=present

- name: Create Application DB User
  mysql_user: name={{ dbuser }} password={{ upassword }} priv=*.*:ALL host='%' state=present
