AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  CloudFrontDistribution:
    Type: String
    Description: 'CloudFrontDistribution ID for which Cloudfront ErrorRate Alarm need to be set'
Resources:
  CloudfrontErrorTopic:
    Type: AWS::SNS::Topic

  CloudfrontErrorEmailSubscriber:
      Type: AWS::SNS::Subscription
      Properties:
        Endpoint: ravinder.thakur@altusgroup.com
        Protocol: email
        TopicArn: !Ref CloudfrontErrorTopic

  CloudFrontTotalErrorRateAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      Namespace: AWS/CloudFront
      MetricName: TotalErrorRate
      Dimensions:
        - Name: DistributionId
          Value: !Ref CloudFrontDistribution
        - Name: Region
          Value: Global
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Threshold: 1
      AlarmActions:
        - !Ref CloudfrontErrorTopic
      TreatMissingData: notBreaching



  CloudFront4xxErrorRateRateAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      Namespace: AWS/CloudFront
      MetricName: 4xxErrorRate
      Dimensions:
        - Name: DistributionId
          Value: !Ref CloudFrontDistribution
        - Name: Region
          Value: Global
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Threshold: 1
      AlarmActions:
        - !Ref CloudfrontErrorTopic
      TreatMissingData: notBreaching


  CloudFront5xxErrorRateRateAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      Namespace: AWS/CloudFront
      MetricName: 5xxErrorRate
      Dimensions:
        - Name: DistributionId
          Value: !Ref CloudFrontDistribution
        - Name: Region
          Value: Global
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Threshold: 1
      AlarmActions:
        - !Ref CloudfrontErrorTopic
      TreatMissingData: notBreaching
