apiVersion: v1
kind: DeploymentConfig
metadata:
  name: rabbitmq
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.6.6-management-alpine
        ports:
        - containerPort: 5672
          name: amqp
        - containerPort: 4369
          name: epmd
        - containerPort: 25672
          name: rabbitmq-dist
        - containerPort: 15672
          name: rabitmanagement

---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: rabbitmq-mgmt
  name: rabbitmq-mgmt
spec:
  ports:
    - port: 15672
  selector:
    app:  rabbitmq
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  labels:
    name: rabbitmq
  name: rabbitmq
spec:
  ports:
    - port: 5672
  selector:
    app: rabbitmq
