apiVersion: v1
kind: DeploymentConfig
metadata:
  name: logstash
  namespace: newapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - name: logstash
        image: rsthakur83/logstash
        ports:
        - containerPort: 5000
        volumeMounts:
            - mountPath: /etc/logstash/conf.d
              name: logstash-staging-sidekiq
      volumes:
       - name: logstash-staging-sidekiq
         configMap:
            name: logstash-staging-sidekiq
            items:
             - key: config
               path: logstash.conf
