apiVersion: v1
kind: DeploymentConfig
metadata:
  name: writer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: writer
    spec:
      containers:
      - name: writer
        image: rsthakur83/writer
