apiVersion: v1
kind: DeploymentConfig
metadata:
  name: cadvisor
  namespace: newapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cadvisor
    spec:
      containers:
      - name: cadvisor
        image: google/cadvisor:latest
        ports:
        - containerPort: 8080
