apiVersion: v1
kind: DeploymentConfig
metadata:
  name: elasticsearch
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image:  docker.elastic.co/elasticsearch/elasticsearch:6.0.1
        resources:
          requests:
            memory: "3228Mi"
            cpu: "1000m"
        ports:
        - containerPort: 9200
