kind: Namespace
apiVersion: v1
metadata:
  name: myapp
  labels:
    name: myapp
---    
apiVersion: v1
kind: Service
metadata:
  name: mynginx
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: mynginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: myapp
  name: mynginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mynginx
  template:
    metadata:
      labels:
        app: mynginx
    spec:
      containers:
      - name: mynginx
        image: rsthakur83/nginx
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 300m        
        ports:
        - containerPort: 80

