apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: telegraf-deployment
spec:
  selector:
    matchLabels:
      app: telegraf
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      serviceAccountName: telegraf-reader
      containers:
        - image: telegraf:1.11
          name: telegraf
          volumeMounts:
            - mountPath: /etc/telegraf/telegraf.conf
              name: telegraf-config
              subPath: telegraf.conf
              readOnly: true
          envFrom:
            - secretRef:
                name: telegraf-secrets
          env:
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
      volumes:
        - name: telegraf-config
          configMap:
            name: telegraf-config

