apiVersion: v1

kind: Secret
metadata:
  name: telegraf-secrets
type: Opaque
stringData:
  INFLUXDB_DB: metrics
  INFLUXDB_URL: http://enter-vm-public-ip:8086
  INFLUXDB_USER: username
  INFLUXDB_USER_PASSWORD: influxdb-password
