apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: consul
spec:
  serviceName: consul
  replicas:  3
  template:
    metadata:
      labels:
        app: consul
    spec:
      containers:
      - name: consul
        env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP          
        #image: clusterconsul
        #image: docker.io/rsthakur83/consul ## with bootstrap enabled for all getting alert
        image: docker.io/rsthakur83/consul-u-bootstrap
        ports:
           
          - containerPort: 8500
            name: ui-port
          - containerPort:  8400
            name: alt-port
          - containerPort: 53
            name: udp-port
          - containerPort:  8600
            name: consuldns
          - containerPort:  8301
            name: serflan
          - containerPort: 8600
            name: serfwan
          - containerPort:  8300
            name: server


############## OPTIONAL FOR ADDING PV & PVC #############
        volumeMounts:
        - name: consul
          mountPath: /opt/consul
  volumeClaimTemplates:
  - metadata:
      name: consul
      annotations:
        volume.alpha.kubernetes.io/storage-class: anything
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi # make this bigger in production
