apiVersion: v1
kind: DeploymentConfig
metadata:
  name: prometheus
  namespace: newapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        #image: prom/prometheus
        #        image: rsthakur83/prometheus
        image: rsthakur83/prometheusnew
        ports:
        - containerPort: 9090
