apiVersion: v1
kind: DeploymentConfig
metadata:
  name: grafana
  namespace: newapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana
        ports:
        - containerPort: 3000
